#!/usr/bin/env node

// Compare decode and attention-to-MoE reports generated by
// analyze_msprof_decode.js and msprof_gap_analysis.js.
//
// Usage:
//   node compare_msprof_prefetch_reports.js \
//     BASE.decode.json LEGACY.decode.json QMLA.decode.json \
//     BASE.gap.json LEGACY.gap.json QMLA.gap.json \
//     [--tail-steps=20] [--pretty]

"use strict";

const fs = require("fs");

const args = process.argv.slice(2);
const files = args.filter(argument => !argument.startsWith("--"));
const tailOption = args.find(argument => argument.startsWith("--tail-steps="));
const tailSteps = tailOption === undefined
  ? 20
  : Number.parseInt(tailOption.split("=")[1], 10);
const pretty = args.includes("--pretty");

if (files.length !== 6 || !Number.isInteger(tailSteps) || tailSteps < 1) {
  throw new Error(
    "usage: node compare_msprof_prefetch_reports.js " +
    "BASE.decode.json LEGACY.decode.json QMLA.decode.json " +
    "BASE.gap.json LEGACY.gap.json QMLA.gap.json " +
    "[--tail-steps=20] [--pretty]",
  );
}

const load = file => JSON.parse(fs.readFileSync(file, "utf8"));
const [baseDecode, legacyDecode, qmlaDecode, baseGap, legacyGap, qmlaGap] =
  files.map(load);

function quantile(values, q) {
  if (values.length === 0) return null;
  const sorted = [...values].sort((left, right) => left - right);
  return sorted[Math.min(
    sorted.length - 1,
    Math.floor(q * sorted.length),
  )];
}

function stats(values) {
  const finite = values.filter(Number.isFinite);
  if (finite.length === 0) return {n: 0};
  return {
    n: finite.length,
    avg: finite.reduce((sum, value) => sum + value, 0) / finite.length,
    p50: quantile(finite, 0.5),
    p90: quantile(finite, 0.9),
    min: Math.min(...finite),
    max: Math.max(...finite),
  };
}

function stableRecords(report) {
  return report.records.filter(record => record.fromEnd <= tailSteps);
}

const recordFields = [
  "layerLatency",
  "attention",
  "preGatingGap",
  "dispatch",
  "gmm1",
  "gmm2",
  "combine",
  "prefetchMla",
  "prefetchIndexer",
  "prefetchLookup",
  "prefetchGather",
  "mlaOverlapGap",
  "indexerOverlapGap",
  "indexerOverlapDispatch",
  "lookupOverlapGap",
  "lookupOverlapDispatch",
  "lookupOverlapGmm1",
  "lookupOverlapGmm2",
  "lookupOverlapCombine",
  "gatherOverlapGap",
  "gatherOverlapDispatch",
  "gatherOverlapGmm1",
  "gatherOverlapGmm2",
  "gatherOverlapCombine",
];

function summarizeRecords(records) {
  return Object.fromEntries(recordFields.map(field => [
    field,
    stats(records.map(record => record[field])),
  ]));
}

function deltaValue(after, before) {
  if (!Number.isFinite(after) || !Number.isFinite(before)) return null;
  const absolute = after - before;
  return {
    absolute,
    percent: before === 0 ? null : absolute / before * 100,
  };
}

function deltaStats(after, before) {
  return Object.fromEntries(
    ["avg", "p50", "p90"].map(field => [
      field,
      deltaValue(after?.[field], before?.[field]),
    ]),
  );
}

function compareSummaries(after, before) {
  return Object.fromEntries(recordFields.map(field => [
    field,
    deltaStats(after[field], before[field]),
  ]));
}

function lookupKernelStats(decodeReport, pattern) {
  return decodeReport.prefetchKernelStats.find(kernel =>
    pattern.test(kernel.name),
  ) ?? {n: 0};
}

function kernelSummary(decodeReport) {
  return {
    mainMla: decodeReport.kernels.mainMla,
    prefetchMla: decodeReport.kernels.prefetchMla,
    prefetchIndexer: decodeReport.kernels.prefetchIndexer,
    prefetchLookup: lookupKernelStats(
      decodeReport,
      /^AsuHbmIndexLookup(?:Opt)?$/,
    ),
    mainGather: decodeReport.gatherStats.main,
    prefetchGather: decodeReport.gatherStats.prefetch,
  };
}

function compareKernelSummaries(after, before) {
  const afterSummary = kernelSummary(after);
  const beforeSummary = kernelSummary(before);
  return Object.fromEntries(Object.keys(afterSummary).map(name => [
    name,
    deltaStats(afterSummary[name], beforeSummary[name]),
  ]));
}

const reports = {
  base: {decode: baseDecode, gap: baseGap},
  legacy: {decode: legacyDecode, gap: legacyGap},
  qmla: {decode: qmlaDecode, gap: qmlaGap},
};

const stable = Object.fromEntries(Object.entries(reports).map(
  ([name, report]) => {
    const records = stableRecords(report.gap);
    const layers = [...new Set(records.map(record => record.layer))]
      .sort((left, right) => left - right);
    const stableStepHistory = report.decode.stableStepHistory ?? [];
    return [name, {
      recordCount: records.length,
      step: report.decode.stableStep,
      anchoredLayers: stats(stableStepHistory.map(
        step => step.anchoredLayerDuration,
      )),
      stepRemainder: stats(stableStepHistory.map(
        step => step.stepRemainder,
      )),
      allMoeLayer: report.gap.aggregate,
      moeLayer: summarizeRecords(records),
      perLayer: Object.fromEntries(layers.map(layer => [
        layer,
        summarizeRecords(records.filter(record => record.layer === layer)),
      ])),
      kernels: kernelSummary(report.decode),
    }];
  },
));

function compareStable(after, before) {
  const layers = Object.keys(after.perLayer).filter(
    layer => before.perLayer[layer] !== undefined,
  );
  return {
    step: deltaStats(after.step, before.step),
    anchoredLayers: deltaStats(
      after.anchoredLayers,
      before.anchoredLayers,
    ),
    stepRemainder: deltaStats(after.stepRemainder, before.stepRemainder),
    allMoeLayer: compareSummaries(after.allMoeLayer, before.allMoeLayer),
    moeLayer: compareSummaries(after.moeLayer, before.moeLayer),
    perLayer: Object.fromEntries(layers.map(layer => [
      layer,
      compareSummaries(after.perLayer[layer], before.perLayer[layer]),
    ])),
  };
}

const output = {
  tailSteps,
  sourceFiles: {
    base: baseDecode.file,
    legacy: legacyDecode.file,
    qmla: qmlaDecode.file,
  },
  stepCounts: {
    base: baseDecode.stepCount,
    legacy: legacyDecode.stepCount,
    qmla: qmlaDecode.stepCount,
  },
  stable,
  delta: {
    qmlaVsLegacy: {
      ...compareStable(stable.qmla, stable.legacy),
      kernels: compareKernelSummaries(qmlaDecode, legacyDecode),
    },
    qmlaVsBase: {
      ...compareStable(stable.qmla, stable.base),
      kernels: compareKernelSummaries(qmlaDecode, baseDecode),
    },
    legacyVsBase: {
      ...compareStable(stable.legacy, stable.base),
      kernels: compareKernelSummaries(legacyDecode, baseDecode),
    },
  },
};

console.log(JSON.stringify(output, null, pretty ? 2 : 0));
